### ISSUE TITLE
Throwing 401 Unauthorized

### ISSUE THREAD

**Issue by Invincible83** [totaljs/openplatform-application2#1]
Hi, @petersirka 
I noticed that if I create a new Openplatform group (e.g. `User`) without permission to `setup` the app doesn't work. POST with openplatform & token throws `401 Unauthorized`.

Same for `OpenReports`, however `OpenAuth` works perfectly without `setup` permission.

Cheers

**Comment by petersirka** [comment]
Hi @Invincible83.
I have fixed permissions. Thank you.
